//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncgmpToolbar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ncgmpToolbar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChildDrop {
            get {
                object obj = ResourceManager.GetObject("ChildDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap color_wheel {
            get {
                object obj = ResourceManager.GetObject("color_wheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_page {
            get {
                object obj = ResourceManager.GetObject("folder_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;r_OrientationDataPoints_Rules&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FULL_12_7_10 {
            get {
                return ResourceManager.GetString("FULL_12_7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;
        ///&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;
        ///&lt;DomainName&gt;r_OrientationDataPoints_Rules&lt;/DomainName&gt;
        ///&lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;
        ///&lt;MergePolicy&gt;esriMPTD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string full_9_20_11 {
            get {
                return ResourceManager.GetString("full_9_20_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;d_Confidence&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeString&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/MergePolicy&gt;&lt;SplitP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string minRequired {
            get {
                return ResourceManager.GetString("minRequired", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap page_copy {
            get {
                object obj = ResourceManager.GetObject("page_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SibDrop {
            get {
                object obj = ResourceManager.GetObject("SibDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;r_OrientationDataPoints_Rules&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stations {
            get {
                return ResourceManager.GetString("stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;d_Confidence&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeString&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/MergePolicy&gt;&lt;SplitP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topology {
            get {
                return ResourceManager.GetString("topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;r_ContactsAndFaultsConcealed&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/Me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topologyRepresentations {
            get {
                return ResourceManager.GetString("topologyRepresentations", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wrench {
            get {
                object obj = ResourceManager.GetObject("wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;r_OrientationDataPoints_Rules&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZONE11 {
            get {
                return ResourceManager.GetString("ZONE11", resourceCulture);
            }
        }
    }
}
